Добавил файлы для докера
iprevysokov/kidedvisor.com pull request #5
Opened 2024-08-20 09:47 UTC by SpaghetNMeatballs

2024-08-21 11:43 UTC, aleksei-astapoff requested changes
Привет все супер, нужно дописать согласно выбранной реализации.

2024-08-21 11:43 UTC, aleksei-astapoff commented on Dockerfile
> +ENV DEBUG=False\
Может подтянуть данные из . env  файла в самом docker-compose.yml
```
env_file: ../.env
```
env.example лежит на том же месте в проекте как и .env файл. Данные в нем актуальны для разработки.

2024-08-21 11:43 UTC, aleksei-astapoff commented on docker-compose.yml
> +    command: bash -c "python ./backend/manage.py runserver 0.0.0.0:8080"
Запускаем через gunicorn, запуск можно выполнить и в Dockerfile

2024-08-21 11:43 UTC, aleksei-astapoff commented on Dockerfile
> +COPY --chown=worker:worker ./backend ./backend
Мы решили запускать сервис через gunicorn, его можно добавить в зависимости проекта. Или устанавливать в контейнере при создании , пример кода ниже.
```
FROM python:3.11
WORKDIR /app
RUN python -m pip install --upgrade pip
RUN pip install gunicorn==20.1.0
COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir
COPY . .
RUN python manage.py makemigrations
RUN python manage.py collectstatic --noinput
CMD ["gunicorn", "--bind", "0.0.0.0:8080", "kidedvisor.wsgi"]
```

2024-08-22 12:57 UTC, aleksei-astapoff commented
может сделать два файла docker-compose.yml? один для локальных контейнеров второй для сервера?

2024-08-23 11:00 UTC, SpaghetNMeatballs commented
Добавил контейнер для nginx, но со статикой пока проблемы - в ближайшее время постараюсь разобраться

2024-08-23 11:23 UTC, aleksei-astapoff approved these changes

2024-08-23 11:23 UTC, merged